version: '2'
services:
    master:
        image: mdbsrv:latest
        privileged: true
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
        volumes:
            - /Users/Shared:/mdb
        hostname: mdbsrv1
        container_name: mdbsrv1
        networks:
            static-network:
                ipv4_address: 172.20.0.2
        ports:
            - "4001:3306"

    slave1:
        image: mdbsrv:latest
        privileged: true
        depends_on:
            - master
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
        volumes:
            - /Users/Shared:/mdb
        hostname: mdbsrv2
        container_name: mdbsrv2
        networks:
            static-network:
                ipv4_address: 172.20.0.3
        ports:
            - "4002:3306"

    slave2:
        image: mdbsrv:latest
        privileged: true
        depends_on:
            - master
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
        volumes:
            - /Users/Shared:/mdb
        hostname: mdbsrv3
        container_name: mdbsrv3
        networks:
            static-network:
                ipv4_address: 172.20.0.4
        ports:
            - "4003:3306"

    slave3:
        image: mdbsrv:latest
        privileged: true
        depends_on:
            - master
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
        volumes:
            - /Users/Shared:/mdb
        hostname: mdbsrv4
        container_name: mdbsrv4
        networks:
            static-network:
                ipv4_address: 172.20.0.5
        ports:
            - "4004:3306"

    maxscale:
        image: mdbmxscl:latest
        privileged: true
        cap_add:
            - SYS_ADMIN
        security_opt:
            - seccomp:unconfined
        tmpfs:
            - /run
            - /run/lock
        volumes:
            - /Users/Shared:/mdb
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        depends_on:
            - master
            - slave1
            - slave2
            - slave3
        hostname: mdbmxscl
        container_name: mdbmxscl
        networks:
            static-network:
                ipv4_address: 172.20.0.6
        ports:
            - "4006:4006"  # readwrite port
            - "4008:4008"  # readonly port
            - "8989:8989"  # REST API port
networks:
    static-network:
        ipam:
            config:
                - subnet: 172.20.0.0/16
                  ip_range: 172.20.5.0/24
                  gateway: 172.20.5.254
